# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mpls_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mpls_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mpls_service.proto\x12\x04mpls\"N\n\x0cLayerRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\x05\x12\x15\n\rlayer_indices\x18\x02 \x03(\x05\x12\x11\n\titeration\x18\x03 \x01(\x05\"T\n\rLayerResponse\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\x1f\n\x06layers\x18\x02 \x03(\x0b\x32\x0f.mpls.LayerData\x12\x11\n\titeration\x18\x03 \x01(\x05\"R\n\tLayerData\x12\x13\n\x0blayer_index\x18\x01 \x01(\x05\x12\x12\n\nparameters\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\"\'\n\x0fMetadataRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\x05\"|\n\x0cPeerMetadata\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\x19\n\x11\x64\x61ta_distribution\x18\x02 \x03(\x02\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x19\n\x11\x63urrent_iteration\x18\x04 \x01(\x05\x12\x15\n\rcompute_speed\x18\x05 \x01(\x02\"8\n\x10HeartbeatRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"F\n\x11HeartbeatResponse\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\r\n\x05\x61live\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"A\n\x10\x42\x61ndwidthRequest\x12\x14\n\x0crequester_id\x18\x01 \x01(\x05\x12\x17\n\x0fpayload_size_mb\x18\x02 \x01(\x05\"H\n\x11\x42\x61ndwidthResponse\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x32\x81\x02\n\x0bMPLSService\x12\x35\n\nPullLayers\x12\x12.mpls.LayerRequest\x1a\x13.mpls.LayerResponse\x12\x38\n\x0bGetMetadata\x12\x15.mpls.MetadataRequest\x1a\x12.mpls.PeerMetadata\x12<\n\tHeartbeat\x12\x16.mpls.HeartbeatRequest\x1a\x17.mpls.HeartbeatResponse\x12\x43\n\x10MeasureBandwidth\x12\x16.mpls.BandwidthRequest\x1a\x17.mpls.BandwidthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mpls_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAYERREQUEST']._serialized_start=28
  _globals['_LAYERREQUEST']._serialized_end=106
  _globals['_LAYERRESPONSE']._serialized_start=108
  _globals['_LAYERRESPONSE']._serialized_end=192
  _globals['_LAYERDATA']._serialized_start=194
  _globals['_LAYERDATA']._serialized_end=276
  _globals['_METADATAREQUEST']._serialized_start=278
  _globals['_METADATAREQUEST']._serialized_end=317
  _globals['_PEERMETADATA']._serialized_start=319
  _globals['_PEERMETADATA']._serialized_end=443
  _globals['_HEARTBEATREQUEST']._serialized_start=445
  _globals['_HEARTBEATREQUEST']._serialized_end=501
  _globals['_HEARTBEATRESPONSE']._serialized_start=503
  _globals['_HEARTBEATRESPONSE']._serialized_end=573
  _globals['_BANDWIDTHREQUEST']._serialized_start=575
  _globals['_BANDWIDTHREQUEST']._serialized_end=640
  _globals['_BANDWIDTHRESPONSE']._serialized_start=642
  _globals['_BANDWIDTHRESPONSE']._serialized_end=714
  _globals['_MPLSSERVICE']._serialized_start=717
  _globals['_MPLSSERVICE']._serialized_end=974
# @@protoc_insertion_point(module_scope)
