# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mpls_service_pb2 as mpls__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mpls_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MPLSServiceStub(object):
    """Service for distributed MPLS worker communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullLayers = channel.unary_unary(
                '/mpls.MPLSService/PullLayers',
                request_serializer=mpls__service__pb2.LayerRequest.SerializeToString,
                response_deserializer=mpls__service__pb2.LayerResponse.FromString,
                _registered_method=True)
        self.GetMetadata = channel.unary_unary(
                '/mpls.MPLSService/GetMetadata',
                request_serializer=mpls__service__pb2.MetadataRequest.SerializeToString,
                response_deserializer=mpls__service__pb2.PeerMetadata.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/mpls.MPLSService/Heartbeat',
                request_serializer=mpls__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=mpls__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.MeasureBandwidth = channel.unary_unary(
                '/mpls.MPLSService/MeasureBandwidth',
                request_serializer=mpls__service__pb2.BandwidthRequest.SerializeToString,
                response_deserializer=mpls__service__pb2.BandwidthResponse.FromString,
                _registered_method=True)


class MPLSServiceServicer(object):
    """Service for distributed MPLS worker communication
    """

    def PullLayers(self, request, context):
        """Pull specific layers from a peer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetadata(self, request, context):
        """Get peer metadata (data distribution, status)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat for peer discovery and health monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MeasureBandwidth(self, request, context):
        """Stream bandwidth test
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MPLSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullLayers': grpc.unary_unary_rpc_method_handler(
                    servicer.PullLayers,
                    request_deserializer=mpls__service__pb2.LayerRequest.FromString,
                    response_serializer=mpls__service__pb2.LayerResponse.SerializeToString,
            ),
            'GetMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetadata,
                    request_deserializer=mpls__service__pb2.MetadataRequest.FromString,
                    response_serializer=mpls__service__pb2.PeerMetadata.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mpls__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=mpls__service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'MeasureBandwidth': grpc.unary_unary_rpc_method_handler(
                    servicer.MeasureBandwidth,
                    request_deserializer=mpls__service__pb2.BandwidthRequest.FromString,
                    response_serializer=mpls__service__pb2.BandwidthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mpls.MPLSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mpls.MPLSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MPLSService(object):
    """Service for distributed MPLS worker communication
    """

    @staticmethod
    def PullLayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpls.MPLSService/PullLayers',
            mpls__service__pb2.LayerRequest.SerializeToString,
            mpls__service__pb2.LayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpls.MPLSService/GetMetadata',
            mpls__service__pb2.MetadataRequest.SerializeToString,
            mpls__service__pb2.PeerMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpls.MPLSService/Heartbeat',
            mpls__service__pb2.HeartbeatRequest.SerializeToString,
            mpls__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MeasureBandwidth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mpls.MPLSService/MeasureBandwidth',
            mpls__service__pb2.BandwidthRequest.SerializeToString,
            mpls__service__pb2.BandwidthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
